#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Copyright (c) 2016 Rodolfo Castelo Méndez. Dos Tercios de Shell
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the ""Software""), to deal in the Software without restriction, including without limitation the rights # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR # COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#
# Module manifest for module 'DTS'
#
# Generated by: Rodolfo Castelo Méndez
#
# Generated on: 10/06/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DTS.psm1'

# Version number of this module.
ModuleVersion = '1.2.0'

# ID used to uniquely identify this module
GUID = '35c70644-f1f2-4850-8af4-f7a4cbe9688e'

# Author of this module
Author = 'Rodolfo Castelo Mendez'

# Company or vendor of this module
CompanyName = 'Dos tercios de Shell'

# Copyright statement for this module
Copyright = '(c) 2016 Rodolfo Castelo Méndez. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'DTS Modules brings simple commands for do hard things, or maybe things have a lot of commands more.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('Cmdlets\DTS-Hardware.psm1','Cmdlets\DTS-Office365.psm1','Cmdlets\DTS-Globales.psm1','Cmdlets\DTS-Sistema.psm1','Cmdlets\DTS-CRM.psm1','Cmdlets\DTS-Internal.psm1','Cmdlets\DTS-External.psm1')

# Functions to export from this module
FunctionsToExport = 'Get-PROArchitecture','Add-PSCustomLocation','Update-DTSModules','Connect-O365Services','Get-FilePath','Get-OSBuild','Get-FolderPath','Import-CRMSDKModule','Connect-CRMOnlineServices','Get-SelectedTime','Get-TextBox','Test-CRMOnlineServices','Add-CRMActivityLastInformation','Get-CRMAvailableActivities','Confirm-InteractiveEnviroment','ConvertFrom-HTMLtoMail','Send-EmailMessage','Send-BulkMail','Test-CSVHeader'

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = 'https://dosterciosdeshell.files.wordpress.com/2016/06/logo-mbr-support-fb1.png'

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
 HelpInfoURI = 'http://dosterciosdeshell.wordpress.com'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}