Enable-Mailbox -Identity alex.segura@tecnofor.pe -Archive
Enable-Mailbox -Identity cesar.carreno@tecnofor.pe -Archive
Enable-Mailbox -Identity deisi.perez@tcreatividad.com -Archive
Enable-Mailbox -Identity despacho@tcreatividad.com -Archive
Enable-Mailbox -Identity erios@tcreatividad.com -Archive
Enable-Mailbox -Identity erodas@tcreatividad.com -Archive
Enable-Mailbox -Identity esther.tapia@tecnofor.pe -Archive
Enable-Mailbox -Identity garantias@tcreatividad.com -Archive
Enable-Mailbox -Identity hrobles@fasscorp.com.pe -Archive
Enable-Mailbox -Identity lissette.rodriguez@tecnofor.pe -Archive
Enable-Mailbox -Identity lucia.anaya@tecnofor.pe -Archive
Enable-Mailbox -Identity renting@tcreatividad.com -Archive
Enable-Mailbox -Identity maria.vasquez@tcreatividad.com -Archive
Enable-Mailbox -Identity mperez@tcreatividad.com -Archive
Enable-Mailbox -Identity caliaga@tcreatividad.com -Archive
Enable-Mailbox -Identity novedades@tecnofor.pe -Archive
Enable-Mailbox -Identity operaciones@tecnofor.pe -Archive
Enable-Mailbox -Identity patricia.navarro@tecnofor.pe -Archive
Enable-Mailbox -Identity ptarazona@tcreatividad.com -Archive
Enable-Mailbox -Identity rcornejo@tcreatividad.com -Archive
Enable-Mailbox -Identity rguerrero@tcreatividad.com -Archive
Enable-Mailbox -Identity rocio.paz@tecnofor.pe -Archive
Enable-Mailbox -Identity rodolfo.castelo@tcreatividad.com -Archive
Enable-Mailbox -Identity rossana.reccio@tecnofor.pe -Archive
Enable-Mailbox -Identity ruth.mamani@tecnofor.pe -Archive
Enable-Mailbox -Identity sertecfa@tcreatividad.com -Archive
Enable-Mailbox -Identity transportestc@tcreatividad.com -Archive
Enable-Mailbox -Identity ventas10@consultoriapym.com -Archive
Enable-Mailbox -Identity ventascorporativas@tecnofor.pe -Archive