Get-Mailbox alex.segura@tecnofor.pe | Select RetentionPolicy
Get-Mailbox cesar.carreno@tecnofor.pe | Select RetentionPolicy
Get-Mailbox deisi.perez@tcreatividad.com | Select RetentionPolicy
Get-Mailbox despacho@tcreatividad.com | Select RetentionPolicy
Get-Mailbox erios@tcreatividad.com | Select RetentionPolicy
Get-Mailbox erodas@tcreatividad.com | Select RetentionPolicy
Get-Mailbox esther.tapia@tecnofor.pe | Select RetentionPolicy
Get-Mailbox garantias@tcreatividad.com | Select RetentionPolicy
Get-Mailbox hrobles@fasscorp.com.pe | Select RetentionPolicy
Get-Mailbox lissette.rodriguez@tecnofor.pe | Select RetentionPolicy
Get-Mailbox lucia.anaya@tecnofor.pe | Select RetentionPolicy
Get-Mailbox renting@tcreatividad.com | Select RetentionPolicy
Get-Mailbox maria.vasquez@tcreatividad.com | Select RetentionPolicy
Get-Mailbox mperez@tcreatividad.com | Select RetentionPolicy
Get-Mailbox caliaga@tcreatividad.com | Select RetentionPolicy
Get-Mailbox novedades@tecnofor.pe | Select RetentionPolicy
Get-Mailbox operaciones@tecnofor.pe | Select RetentionPolicy
Get-Mailbox patricia.navarro@tecnofor.pe | Select RetentionPolicy
Get-Mailbox ptarazona@tcreatividad.com | Select RetentionPolicy
Get-Mailbox rcornejo@tcreatividad.com | Select RetentionPolicy
Get-Mailbox rguerrero@tcreatividad.com | Select RetentionPolicy
Get-Mailbox rocio.paz@tecnofor.pe | Select RetentionPolicy
Get-Mailbox rodolfo.castelo@tcreatividad.com | Select RetentionPolicy
Get-Mailbox rossana.reccio@tecnofor.pe | Select RetentionPolicy
Get-Mailbox ruth.mamani@tecnofor.pe | Select RetentionPolicy
Get-Mailbox sertecfa@tcreatividad.com | Select RetentionPolicy
Get-Mailbox transportestc@tcreatividad.com | Select RetentionPolicy
Get-Mailbox ventas10@consultoriapym.com | Select RetentionPolicy
Get-Mailbox ventascorporativas@tecnofor.pe | Select RetentionPolicy