Write-Host "================================================================================================"
Write-Host "                                         Enjoy your work                                 "
Write-Host "                                  .                          .                           "
Write-Host "                                  ,c.                       :;                           "
Write-Host "                                   'o:.                  .;o,                            "
Write-Host "                                      .cc,.             'cl'                              "
Write-Host "                            '           'cl'        'cc'           ..                    "
Write-Host "                           .xo            .lkccoollOd.            ;0'                    "
Write-Host "                            ,0.          :OXWMMMMMMMWKl          .0d                     "
Write-Host "                             ld         cNMMMMMMMMMMMMWo         dx.                     "
Write-Host "                              c:       .OMMMMMMMMMMMMMMK.       'c.                      "
Write-Host "                               .c;.     oWMMMMMMMMMMMMWO.    .cl.                        "
Write-Host "                                 'ld;.  .xWMMMMMMMMMMWk.  .cOd'                          "
Write-Host "                                    .ckOc. .'l0WMMMKc,. .:O0o.                            "
Write-Host "                                      .dKO; ,NMMMMNc .o0x,                               "
Write-Host "                                        .c0OoNMMMMMKx0l.                                 "
Write-Host "                                          .lXMMMMMMNo.                                   "
Write-Host "                                           'OWMMMMMK;.                                   "
Write-Host "                                    ..;loxxo0NKNWKNNddxol:..                             "
Write-Host "                                .lk0K0d:. .ox,.KX.'xx. .:oOKKOo.                         "
Write-Host "                               .xd.      :k:  ;NWd  :Oc      .ck.                        "
Write-Host "                              ;kc      ,kx.  .xWWO.  .oO;      ;Oc                       "
Write-Host "                            ,dd.     .dKl..cxONMMWNKx,.;0k.     .lx;.                    "
Write-Host "                         .lxo.      .kx. lNMMMMMMMMMMWx..d0.      .cxo'                  "
Write-Host "                      .,dxx,         .x. ,NMMMMMMMMMMMMN: .d.         ,dxd,.              "
Write-Host "                   .:ddl'             o; lNMMMMMMMMMMMMWd .O.            .cdoc'           "
Write-Host "                ,l:'.                co.:NMMMMMMMMMMMMNl :O.                ';l:         "
Write-Host "                                     lx .KMMMMMMMMMMMMX' oO.                             "
Write-Host "                                    .kx  cNMMMMMMMMMMWd  o0.                             "
Write-Host "                                    .0o   lNMMMMMMMMWk.  ;K.                             "
Write-Host "                                    '0,    ;KMMMMMMNl    .K;                             "
Write-Host "                                    c0.     .:x00kl.     .kx                             "
Write-Host "                                   .Oc                    ,0.                            "
Write-Host "                                   'x.                     o;                            "
Write-Host "                                   ;.                      .:                            "
Write-Host "                                                                                         "
Write-Host "================================================================================================"
Write-Host 
#############################################################################################################################