Write-Host 
Write-Host "                                                               Enjoy your work                            "
Write-Host "                                                                     "
Write-Host "                                                                                    c'                                                                         "
Write-Host "                                                                                    o,                                                                         "
Write-Host "                                                                          .         oc                                                                         "
Write-Host "                                                                         .c         dc                                                                         "
Write-Host "                                                                    .    .d.        dd                                                                         "
Write-Host "                                                             .:.    ,;,'..kc        dO.            .                                                           "
Write-Host "                                                              ;o.     .,cdK0l,'''';lOKc            ::.                                                         "
Write-Host "                                                               ,x;.      .00cclll:::lkXo.           ,o.                                                        "
Write-Host "                                                                .ldl;..  .Kk.     .. .dNO,           ,k'                                                       "
Write-Host "                                                                   .:oxxdkNO.     .;;  ;OXo.         .Oc      .                                                "
Write-Host "                                                                       .:ONNx.     .o:   :0Kx,.     .l0;     .o. ;,                                            "
Write-Host "                                                                          ,xXXo.    lO.   .:kKKxl;;dK0;      ;k.;0c.:,                                         "
Write-Host "                                                                            .l0Xkc..;O;      .;kXWWWXl.     'OXx0Xkkd.                                         "
Write-Host "                                                                              .:kXKkOKx.        .;xKKKKOdlcdKNNNNXOc.                                          "
Write-Host "                                                                                 .lxOKX0do:'...'';:x0KXXKXNNNN0o;.                                             "
Write-Host "                                                                                    .:ldkOOOOOkkkkO000XNNNWWWW0l'..                                            "
Write-Host "                                                                                            .    ..lKXNWWWWWWWWWX0xl,.                                         "
Write-Host "                                                                                                  .lOXWWWWWNNNNXKK0OOxc,.                                      "
Write-Host "                                                                                                 .ck0KNNNNNXKXXX0OOOO0XNKOdl,.                                 "
Write-Host "                                                                                               .;oxkkkkkOKXKXNNK0OOO00XNNNKKKO:                                "
Write-Host "                                                                                              'oxxxxkkxkO0KKXXXOkO0000KXNNKKKk'                                "
Write-Host "                                             .':ldkOOOkxo:;,'...                      ..    .:xkkkkkkOkOOOOO0KKOk0XKOkxddolc'                                  "
Write-Host "                                          ,o0XNWMMMWMMWWWNXKK00Oxddoc::cc;,',,,;:codxO00OkxxkkxkkOkkOKK00OOOOOOkl;'..                                          "
Write-Host "                                       ':xNWWWWMMMMMMMMWWWWWNXXK00OOkkOKNNXXXNNXK0KXNWWWWNXK0OkkkOKKXNNNXXKK0Ok;                                               "
Write-Host "                                     ;dO00XNWWWWMMWWNNWNNNWWWWWNXKKKKXNXXXXKKXXKOO0XWWWWWWNXKKKKKXWWWWNNNNXK0k;                                                "
Write-Host "                                   'kNKKK0OO0KXXXWNXXNNXNNXXNWWWWWWWWWWWWWWWNOKNWWNWWWWWWWWNNWWWNWWWWWWWNXK0Ol.                                                "
Write-Host "                                  .kWWWNNX0OO0000XXXKKNNNXKKXWWWWWWWMMMMMMWNd.,0WMMWMMMMWWWWWWWNNWWWWWWNXK0k:                                                  "
Write-Host "                                  ;KWWWWWNXKK00KXNNWXKNWNWWNXNWWWWWWMWMWWWXl.  ,0WMMWMMMWWWWNNXKXNWWWWWNK0k;                                                   "
Write-Host "                                  lNWWWWNXKXWWWWWMMMWWNNWWWNXNWNWWWWMWWWWK;     .0WWWMMWNWNXXXNXXXWWMWWX0x'                                                    "
Write-Host "                                  lWWWWNXKXXWMWMMMMMMWWWWNNXXXXXNWMMMWWNk.       .0WWWMWWWNNNNNNNWWWWWNKo.                                                     "
Write-Host "                                  .kNNNNXXXNWMWMMMMMMWWWNNNNXKXNNWWWWNKo.         'ONWNWWWWNNNNNWWWWWNKl.                                                      "
Write-Host "                                   .:0NWWNNWWWMMMMMMWWNWNNWNXXXNNWWMW0,            .oXXXXXXXNXNWWWWWKx,                                                        "
Write-Host "                                     .oXWWWWWWWMMMWWNNXXNWNNKKNWMWMMW0ddocccclloodooxXKOOOO0KNWWWWWO;.                                                         "
Write-Host "                                       .oXWWWWMMMMWWWWNWNNNXK0XWWMMMMMMWXK00KKXNXXXNNNNKKXXNNWWWWWW0l.                                                         "
Write-Host "                                         .oNWWMMMMWNNNNWNWXXK0XWWWWWWWWWWNK0000K0KXXXNNNWWWWWWWNNWWWWXkc.                                                      "
Write-Host "                                           ;0NWMMWWWNNNNNNX0OOkc.';cx0KXKOkkkkkOKKXNWWWWWWWWWWWWWWWWWWWXxc,.                                                   "
Write-Host "                                             'dWMWWWNKKKK0Oxdo'       ......'',:kXXXWWNNXxcldxxxkO0NWNNKxooc'                                                  "
Write-Host "                                              .0WWWX0OxxOOOkd,                  dNWWWWKc.         .;kXX0kdo:.                                                  "
Write-Host "                                              .xWWNXK0kxxOkl.                  .kWWWWNc         .'ldddool;.                                                    "
Write-Host "                                             'oXWWWNNNXKk;.                    .OWWNNx.    ..:ooddol:'.                                                        "
Write-Host "                                            lNWWMWMMMMMK.                      :KWNNO..,:odO0K0Ox:.                                                            "
Write-Host "                                            :OXWWMWWWWMK'                    :ONWNNN0OKXNNXK0d:.                                                               "
Write-Host "                                              .;xKNWWWWWXx:.                oNWWWNXNXXK0xo;.                                                                   "
Write-Host "                                                  .lXWMWWWWN0c'            '0WWWWKc....                                                                        "
Write-Host "                                                    'kWMWWWWWWNKx:.        .cNWWNx.                                                                            "
Write-Host "                                                     .lKK00Odx0XWWN0o,.    .xWWNO.                                                                             "
Write-Host "                                                       'xkkkd...,o0NWNXOo,'oXWNk'                                                                              "
Write-Host "                                                        .:xkkkc.   .cxXWWWNWWW0;                                                                               "
Write-Host "                                                          'kKOko.     .:XMWWWWk.                                                                               "
Write-Host "                                                           .lkkxd:.     ;NWXXXc                                                                                "
Write-Host "                                                             ,00Oxd'    xWWNN0.                                                                                "
Write-Host "                                                              .:dKN0'   oWWWWK.                                                                                "
Write-Host "                                                                 .,,.   .kWWWX'                                                                                "
Write-Host "                                                                         .xNWWx.                                                                               "
Write-Host "                                                                           .;::'                                                                               "
Write-Host "                                                                                                                                                                "